### ISSUE TITLE
WhereYouGo reports Connection error

### ISSUE THREAD

**Issue by Lineflyer** [biylda/WhereYouGo#1]
Hi,

writing to you from the [c:geo](https://github.com/cgeo/cgeo) developer team.
We recently posted on social networks that c:geo is able to start WhereYouGo from the cache listing and directly invoke download of the cartridge.
However some users replied (and we even have such a verified case on our support mail), that they get a connection error while WhereYouGo tries to login although correct logindata is stored and they are using the newest version available on GooglePlay.

Any ideas how to debug and fix?
Sadly for myself it is working flawless, so I can't be of any big help. It seems to be depending on the device or the user account.

Edit: Crossposted to https://github.com/Kim-tae-yong/android-whereyougo/issues/9 as I don't know which is the correct repo.

**Comment by biylda** [comment]
Hi,
wherigo.com started using TLSv1.2, so I rewrote downloading feature in https://github.com/biylda/WhereYouGo/commit/ed2a4d46ac13064ac85527a2e2a4df049cada62e accordingly.

**Comment by Lineflyer** [comment]
Did you publish this change to Google Play already?
I do see a v0.90 release here on Github from some days ago, however on GooglePlay the version is still shown from 2014.

**Comment by biylda** [comment]
I published it today on Google Play

**Comment by Lineflyer** [comment]
Thanks!
I published a small note on c:geo Facebook and G+ page telling the users, that there is a new version.
Some already confirmed the fix there!
