### ISSUE TITLE
Play anywhere starting location

### ISSUE THREAD

**Issue by Landsbanki** [biylda/WhereYouGo#32]
I've created 5 play anywhere cartridges for a mega event. We folks from all over Europe trying to play the cartridges but folks are finding the zones are being created several Kms from their position. The further they are from the starting coordinates the greater the problem. The issue is restricted to WhereYouGo users. iPhone users are starting in the correct position. It would be great if a fix could be found as we're getting inundated with requests for help from WhereYouGo users.

**Comment by SchoolGuy** [comment]
@Landsbanki The users should check if both GPS inside WhereYouGo and their phone is switched on. I had similar problems with my play anywhere cartridges and it was never the fault of the app, always a user made problem.

**Comment by Landsbanki** [comment]
Apparently it's a known bug that is being created by the Earwigo builder. I'm waiting to hear back from the developer of the builder as there is a fix.
