### ISSUE TITLE
Improve german Google Play translation

### ISSUE THREAD

**Issue by Lineflyer** [biylda/WhereYouGo#5]
The current german Google Play translation seems to be auto-translated which makes it really hard to understand.
I can volnuteer to create a proper description (and change log if needed) if someone can establish a method to do this (e.g. include in some file here or create a Github wiki page as source to copy it from when publishing on Google Play).

**Comment by biylda** [comment]
That would be cool. For now, German description and changelog (max. 500 characters) for Google Play are here:
https://github.com/biylda/WhereYouGo/blob/master/_data/desc_de.txt
https://github.com/biylda/WhereYouGo/blob/master/_data/changelog_de.txt
